In [ ]:
import numpy as np

#1. Create:

In [ ]:
data = np.random.rand(2,3,4) # Create an array with random numbers
zeros = np.zeros((2,2,2)) # Create an array only with zero values
full = np.full((2,2,2), 7) # Create an array only with numbers that we can choose
ones = np.ones((2,2,2)) # Create an array only with one values

In [ ]:
data

array([[[0.68806807, 0.60297696, 0.41925235, 0.25002332],
        [0.15814926, 0.64909329, 0.43201163, 0.4617894 ],
        [0.83245378, 0.4056968 , 0.77881527, 0.68393391]],

       [[0.47559482, 0.55778569, 0.75724184, 0.41796304],
        [0.90163361, 0.33949593, 0.9273789 , 0.92303246],
        [0.66549549, 0.64566282, 0.40880388, 0.97176897]]])

In [ ]:
zeros

array([[[0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.]]])

In [ ]:
full

array([[[7, 7],
        [7, 7]],

       [[7, 7],
        [7, 7]]])

In [ ]:
ones

array([[[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]]])

In [ ]:
arr = np.array([[1,2,3,4], [1,2,3,4]])
arr

array([[1, 2, 3, 4],
       [1, 2, 3, 4]])

In [ ]:
type(arr)

numpy.ndarray

#2. Read:

In [ ]:
# Attributes
shape = data.shape
size = data.size
types = data.dtype

In [ ]:
shape

(2, 3, 4)

In [ ]:
size

24

In [ ]:
types

dtype('float64')

In [ ]:
# Slicing
arr = data[0] # Show the first array
#slicer = data[0:2] # Slice the array a little bit
slicer = data[0][0:2] # Slice the array to show just only the first array
reverse = data[-1] # Show only the last array
singleval = data[0][0][0] # Showing a single array value

In [ ]:
arr

array([[0.68806807, 0.60297696, 0.41925235, 0.25002332],
       [0.15814926, 0.64909329, 0.43201163, 0.4617894 ],
       [0.83245378, 0.4056968 , 0.77881527, 0.68393391]])

In [ ]:
slicer

array([[0.68806807, 0.60297696, 0.41925235, 0.25002332],
       [0.15814926, 0.64909329, 0.43201163, 0.4617894 ]])

In [ ]:
reverse

array([[0.47559482, 0.55778569, 0.75724184, 0.41796304],
       [0.90163361, 0.33949593, 0.9273789 , 0.92303246],
       [0.66549549, 0.64566282, 0.40880388, 0.97176897]])

In [ ]:
singleval

0.6880680672912438

#3. Update:

In [ ]:
list1 = np.random.rand(10)
list2 = np.random.rand(10)

In [ ]:
list1

array([0.72035806, 0.14503088, 0.13960705, 0.96589686, 0.16909952,
       0.61517378, 0.95092311, 0.88338819, 0.79627936, 0.57978678])

In [ ]:
list2

array([0.1391733 , 0.41551266, 0.91456231, 0.96815191, 0.34925028,
       0.7366808 , 0.30902384, 0.01996675, 0.62124302, 0.7681046 ])

In [ ]:
# Basic Math

add = np.add(list1, list2)
sub = np.subtract(list1, list2)
div = np.divide(list1, list2)
mult = np.multiply(list1, list2)
dot = np.dot(list1, list2) # Multiply everything all together

In [ ]:
add

array([0.85953136, 0.56054355, 1.05416936, 1.93404877, 0.5183498 ,
       1.35185458, 1.25994695, 0.90335494, 1.41752238, 1.34789138])

In [ ]:
sub

array([ 0.58118476, -0.27048178, -0.77495526, -0.00225504, -0.18015076,
       -0.12150702,  0.64189927,  0.86342145,  0.17503634, -0.18831781])

In [ ]:
div

array([ 5.17597891,  0.34904083,  0.15264903,  0.99767077,  0.48417863,
        0.83506151,  3.07718366, 44.24297431,  1.28175179,  0.7548279 ])

In [ ]:
mult

array([0.10025461, 0.06026217, 0.12767935, 0.93513489, 0.05905805,
       0.45318671, 0.29385791, 0.01763839, 0.49468299, 0.44533689])

In [ ]:
dot

2.9870919596124925

In [ ]:
# Stat functions

sqtr = np.sqrt(25)
ab = np.abs(-2)
power = np.power(2,7)
log = np.log(25)
exp = np.exp([2,3])
mins = np.min(list1)
maxs = np.max(list1)

In [ ]:
sqtr

5.0

In [ ]:
ab

2

In [ ]:
power

128

In [ ]:
log

3.2188758248682006

In [ ]:
exp

array([ 7.3890561 , 20.08553692])

In [ ]:
mins

0.13960705324363198

In [ ]:
max

<function max>

In [ ]:
# Updating the value
data[0][0][0] = 700
data

array([[[7.00000000e+02, 6.02976960e-01, 4.19252353e-01, 2.50023315e-01],
        [1.58149262e-01, 6.49093294e-01, 4.32011633e-01, 4.61789400e-01],
        [8.32453776e-01, 4.05696805e-01, 7.78815267e-01, 6.83933905e-01]],

       [[4.75594825e-01, 5.57785689e-01, 7.57241837e-01, 4.17963045e-01],
        [9.01633609e-01, 3.39495931e-01, 9.27378900e-01, 9.23032460e-01],
        [6.65495487e-01, 6.45662821e-01, 4.08803875e-01, 9.71768972e-01]]])

In [ ]:
data.sort()
data

array([[[2.50023315e-01, 4.19252353e-01, 6.02976960e-01, 7.00000000e+02],
        [1.58149262e-01, 4.32011633e-01, 4.61789400e-01, 6.49093294e-01],
        [4.05696805e-01, 6.83933905e-01, 7.78815267e-01, 8.32453776e-01]],

       [[4.17963045e-01, 4.75594825e-01, 5.57785689e-01, 7.57241837e-01],
        [3.39495931e-01, 9.01633609e-01, 9.23032460e-01, 9.27378900e-01],
        [4.08803875e-01, 6.45662821e-01, 6.65495487e-01, 9.71768972e-01]]])

In [ ]:
# Reshape the array
data = data.reshape((2,2,-1)) # -1 means that we don't care what the last value is going to be
data.shape

(2, 2, 6)

In [ ]:
zeroes = np.zeros((8))
print(zeroes)
zeroes = np.append(zeroes, [3, 4]) # Append will insert the value in the end of the array
print(zeroes)

[0. 0. 0. 0. 0. 0. 0. 0.]
[0. 0. 0. 0. 0. 0. 0. 0. 3. 4.]


In [ ]:
zeroes = np.insert(zeroes, 2, 1) # Insert the value where we want it to be
print(zeroes)

[0. 0. 1. 0. 0. 0. 0. 0. 0. 3. 4.]


#4. Delete

In [ ]:
data

array([[[2.50023315e-01, 4.19252353e-01, 6.02976960e-01, 7.00000000e+02,
         1.58149262e-01, 4.32011633e-01],
        [4.61789400e-01, 6.49093294e-01, 4.05696805e-01, 6.83933905e-01,
         7.78815267e-01, 8.32453776e-01]],

       [[4.17963045e-01, 4.75594825e-01, 5.57785689e-01, 7.57241837e-01,
         3.39495931e-01, 9.01633609e-01],
        [9.23032460e-01, 9.27378900e-01, 4.08803875e-01, 6.45662821e-01,
         6.65495487e-01, 9.71768972e-01]]])

In [ ]:
np.delete(data, 0, axis=1) # Delete a row o a column in the array.

array([[[0.4617894 , 0.64909329, 0.4056968 , 0.68393391, 0.77881527,
         0.83245378]],

       [[0.92303246, 0.9273789 , 0.40880388, 0.64566282, 0.66549549,
         0.97176897]]])

In [ ]:
np.save("New array", data) # Save the array

In [ ]:
test = np.load("New array.npy") # Load the data

In [ ]:
test

array([[[2.50023315e-01, 4.19252353e-01, 6.02976960e-01, 7.00000000e+02,
         1.58149262e-01, 4.32011633e-01],
        [4.61789400e-01, 6.49093294e-01, 4.05696805e-01, 6.83933905e-01,
         7.78815267e-01, 8.32453776e-01]],

       [[4.17963045e-01, 4.75594825e-01, 5.57785689e-01, 7.57241837e-01,
         3.39495931e-01, 9.01633609e-01],
        [9.23032460e-01, 9.27378900e-01, 4.08803875e-01, 6.45662821e-01,
         6.65495487e-01, 9.71768972e-01]]])